/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
export * from './apis/base-controller-api';
export * from './apis/institution-controller-api';
export * from './apis/license-controller-api';
export * from './apis/login-controller-api';
export * from './apis/registration-controller-api';
export * from './apis/user-controller-api';

