/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import {
    
} from ".";

/**
 * 
 *
 * @export
 * @interface Country
 */
export interface Country {

    /**
     * @type {string}
     * @memberof Country
     */
    id?: string;

    /**
     * @type {string}
     * @memberof Country
     */
    name: string;

    /**
     * @type {string}
     * @memberof Country
     */
    isoCode: string;
}
