/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { Address } from './address';
import {
    Address,
} from ".";

/**
 * 
 *
 * @export
 * @interface Institution
 */
export interface Institution {

    /**
     * @type {string}
     * @memberof Institution
     */
    id?: string;

    /**
     * @type {string}
     * @memberof Institution
     */
    name: string;

    /**
     * @type {Address}
     * @memberof Institution
     */
    address?: Address;

    /**
     * @type {string}
     * @memberof Institution
     */
    addressId?: string;
}
