/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { LicenseModel } from './license-model';

/**
 * 
 *
 * @export
 * @interface LicenseOption
 */
export interface LicenseOption {

    /**
     * @type {string}
     * @memberof LicenseOption
     */
    id: string;

    /**
     * @type {LicenseModel}
     * @memberof LicenseOption
     */
    model: LicenseModel;
}
