/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import {
    
} from ".";

/**
 * 
 *
 * @export
 * @interface Price
 */
export interface Price {

    /**
     * @type {string}
     * @memberof Price
     */
    subject: string;

    /**
     * @type {number}
     * @memberof Price
     */
    unitPrice: number;

    /**
     * @type {string}
     * @memberof Price
     */
    currency?: PriceCurrencyEnum;
}

/**
 * @export
 * @enum {string}
 */
export enum PriceCurrencyEnum {
    BritishPoundSterling = 'British Pound Sterling',
    UnitedStatesDollar = 'United States Dollar',
    Euro = 'Euro'
}

