/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { Institution } from './institution';

/**
 * 
 *
 * @export
 * @interface Profile
 */
export interface Profile {

    /**
     * @type {string}
     * @memberof Profile
     */
    id?: string;

    /**
     * @type {string}
     * @memberof Profile
     */
    title: ProfileTitleEnum;

    /**
     * @type {string}
     * @memberof Profile
     */
    highestEducation: ProfileHighestEducationEnum;

    /**
     * @type {Institution}
     * @memberof Profile
     */
    almaMater?: Institution;

    /**
     * @type {string}
     * @memberof Profile
     */
    primaryInterest: string;

    /**
     * @type {string}
     * @memberof Profile
     */
    secondaryInterest?: string;

    /**
     * @type {Array<string>}
     * @memberof Profile
     */
    tertiaryInterests?: Array<string>;
}

/**
 * @export
 * @enum {string}
 */
export enum ProfileTitleEnum {
    Chancellor = 'Chancellor',
    ViceChancellor = 'Vice-Chancellor',
    HonoraryProfessor = 'Honorary Professor',
    Professor = 'Professor',
    Director = 'Director',
    Doctor = 'Doctor',
    Mr = 'Mr',
    Ms = 'Ms',
    Other = 'Other'
}
/**
 * @export
 * @enum {string}
 */
export enum ProfileHighestEducationEnum {
    DoctoralDegree = 'Doctoral Degree',
    MastersDegree = 'Master\'s Degree',
    BachelorsDegree = 'Bachelor\'s Degree',
    Diploma = 'Diploma',
    Other = 'Other'
}

