/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { LicenseModel } from './license-model';
import { User } from './user';

/**
 * 
 *
 * @export
 * @interface UserLicense
 */
export interface UserLicense {

    /**
     * @type {LicenseModel}
     * @memberof UserLicense
     */
    licenseModel: LicenseModel;

    /**
     * @type {User}
     * @memberof UserLicense
     */
    licensedUnder: User;
}
