/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { GrantedAuthority } from './granted-authority';
import { Institution } from './institution';
import { Profile } from './profile';
import { Role } from './role';
import { UserLicense } from './user-license';

/**
 * 
 *
 * @export
 * @interface User
 */
export interface User {

    /**
     * @type {string}
     * @memberof User
     */
    id?: string;

    /**
     * @type {string}
     * @memberof User
     */
    username: string;

    /**
     * @type {string}
     * @memberof User
     */
    password: string;

    /**
     * @type {string}
     * @memberof User
     */
    firstName: string;

    /**
     * @type {string}
     * @memberof User
     */
    lastName: string;

    /**
     * @type {string}
     * @memberof User
     */
    email: string;

    /**
     * @type {string}
     * @memberof User
     */
    phone?: string;

    /**
     * @type {Array<Role>}
     * @memberof User
     */
    roles?: Array<Role>;

    /**
     * @type {Institution}
     * @memberof User
     */
    institution?: Institution;

    /**
     * @type {Profile}
     * @memberof User
     */
    profile?: Profile;

    /**
     * @type {UserLicense}
     * @memberof User
     */
    license?: UserLicense;

    /**
     * @type {boolean}
     * @memberof User
     */
    hasConsentForDataSharing?: boolean;

    /**
     * @type {boolean}
     * @memberof User
     */
    hasAgreedTerms?: boolean;

    /**
     * @type {boolean}
     * @memberof User
     */
    accountNonExpired?: boolean;

    /**
     * @type {boolean}
     * @memberof User
     */
    accountNonLocked?: boolean;

    /**
     * @type {boolean}
     * @memberof User
     */
    credentialsNonExpired?: boolean;

    /**
     * @type {boolean}
     * @memberof User
     */
    enabled?: boolean;

    /**
     * @type {Array<GrantedAuthority>}
     * @memberof User
     */
    authorities?: Array<GrantedAuthority>;
}
